### ISSUE TITLE
Add `--format posix` argument to `tar` to support caching DerivedData

### ISSUE THREAD

**Issue by jflan-dd** [bitrise-steplib/bitrise-step-save-cache#32]
### Troubleshooting

- [x] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.3.1
- Is the issue reproducible with the latest version? YES
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Issue description

I've been attempting to replicate the work from [this article](https://michalzaborowski.medium.com/circleci-60-faster-builds-use-xcode-deriveddata-for-caching-96fb9a58930) for our Bitrise builds.

Using the standard Save Cache and Restore Cache I wasn't able to have Xcode reuse any build artifacts, and it actually ended up taking more time than without the cache.

After going through the differences between the steps in the article and the Bitrise Save/Restore Cache steps I found that the important difference was passing `--format posix` to the `tar` command in Save Cache.

I was also able to validate this behavior locally without Bitrise in the loop at all by manually archiving a restoring the DerivedData folder and seeing that Xcode only reused artifacts when `--format posix` was supplied.

### Bitrise info

- Build URL: 
This is the build that create the cache: https://app.bitrise.io/build/a5c7e56a-116f-44cb-8ae6-24846dcd032e
This is the build that reused the cache: https://app.bitrise.io/build/12116908-0e79-4902-8ffb-6a6161f9919a

- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: YES
- Log: 

<details>
  <pre>
 
  </pre>
</details>

### Steps to reproduce

1. ...
2. ...

**Comment by jflan-dd** [comment]
This is the motivation for using the posix format according to the original article
>we will use posix notation for higher-resolution timestamps. This preserves various attributes used by xcodebuild.

**Comment by treastrain** [comment]
Focusing on the discussion of Xcode's cache for DerivedData, I have [bitrise-steplib/bitrise-step-save-xcodebuild-cache](https://github.com/bitrise-steplib/bitrise-step-save-xcodebuild-cache) and [bitrise-steplib/bitrise-step-restore-xcodebuild-cache](https://github.com/bitrise-steplib/bitrise-step-restore-xcodebuild-cache) have started development with strong interest.

These have not yet been added to [bitrise-io/bitrise-steplib](https://github.com/bitrise-io/bitrise-steplib), so it does not appear that we can use them from bitrise.io yet.

**Comment by treastrain** [comment]
Focusing on the discussion of DerivedData provided by Xcode, I am very interested in the [bitrise-steplib/bitrise-step-save-xcodebuild-cache](https://github.com/bitrise-steplib/bitrise-step-save-xcodebuild-cache) and [bitrise-steplib/bitrise-step-restore-xcodebuild-cache](https://github.com/bitrise-steplib/bitrise-step-restore-xcodebuild-cache) are beginning development.


These have not yet been added to [bitrise-io/bitrise-steplib](https://github.com/bitrise-io/bitrise-steplib), so it does not appear that we can use them from bitrise.io yet.

**Comment by bitrise-silver** [comment]
`custom_tar_args` has been added https://github.com/bitrise-steplib/bitrise-step-save-cache?tab=readme-ov-file#%EF%B8%8F-configuration , thanks for your feedback .

**Comment by jflan-dd** [comment]
Thanks!
